### ISSUE TITLE
How to initialize EPCalendarPicker with selected dates?

### ISSUE THREAD

**Issue by shivanraptor** [ipraba/EPCalendarPicker#1]
Dear ipraba,

How to initialize EPCalendarPicker with selected dates?
Users always want to re-pick the dates after they choose.
How to achieve it?

Regards,
Raptor

**Comment by ipraba** [comment]
Dear shivanraptor,

My current implementation only accepts the startYear and endYear of the calendar. I will expose another initialiser which will intake the new dates. Give a day time I will update the pods

**Comment by ipraba** [comment]
Dear shivanraptor,

This has been fixed here https://github.com/ipraba/EPCalendarPicker/commit/019c69e0cf3469129422c7b6c4eb58465fbe634d

I have exposed a initializer with selected dates
           public init(startYear: Int, endYear: Int, multiSelection: Bool, selectedDates: [NSDate]?) 

Incase you use cocoapods kindly update the pods. It will update to v1.0.5

**Comment by shivanraptor** [comment]
Thanks for the update, @ipraba !  Great work !
