### ISSUE TITLE
Disable date selected

### ISSUE THREAD

**Issue by RonakPatel07** [ipraba/EPCalendarPicker#18]
set multiple selection to false then in single selection past date is also selectable.

**Comment by YMonnier** [comment]
Hello, 
I have pulled request to solve this problem. It is still waiting...

YM

**Comment by ipraba** [comment]
Fixed it here https://github.com/ipraba/EPCalendarPicker/commit/0dd4d6d045ebd7c82fcf9c7221c78fb8c398eda4

**Comment by RonakPatel07** [comment]
Thanks!!

**Comment by RonakPatel07** [comment]
Hii..

Why this shows me 1 day before?
when i select any date for ex. i select 21 then its shows me 20

**Comment by ipraba** [comment]
When you print any date the date will be printed based on GMT. If you are in GMT + some hours then it will print it like the time is yesterday. All NSDates are printed always with GMT time and not your local time.
