### ISSUE TITLE
How we can disable a particular date from the Calendar 

### ISSUE THREAD

**Issue by pushpendra996** [ipraba/EPCalendarPicker#22]
Hi, 
Here i am not able to understand, how can i disable any particular date from the calendar view.
Let's suppose today date is **18th June 2016**, before **18th June 2016** all dates is disable but i want disable 
next to **18th June 2016**, example i want to disable **24th June 2016** 
How should i do that please tell me as soon as possible
 Thanks in advance

**Comment by ipraba** [comment]
Sorry currently this library doesn't support. But you can always take a fork and implement it yourself. Thanks

**Comment by pushpendra996** [comment]
Thanks praba
I did implement that functionality by own thanks for your suggestions.
