### ISSUE TITLE
Swift 3.0 Issues

### ISSUE THREAD

**Issue by dylankbuckley** [ipraba/EPCalendarPicker#28]
Just did an update to Swift 3.0 and noticing a few build-time errors:

<img width="327" alt="screen shot 2016-09-15 at 15 02 37" src="https://cloud.githubusercontent.com/assets/8408005/18552701/7d60760c-7b55-11e6-8225-5840a47dfc8f.png">

and:

<img width="633" alt="screen shot 2016-09-15 at 15 03 13" src="https://cloud.githubusercontent.com/assets/8408005/18552715/91efb984-7b55-11e6-96db-8357eddf1383.png">

**Comment by Kireyin** [comment]
About the ambiguous operators : it is because Date is now Comparable in Swift 3 and EPCalendarPicker includes its own Date comparison operators. Delete the Date comparison operator from EPCalendar will fix those issues

**Comment by Kireyin** [comment]
Can you screenshot the concerned code for the other issues @dylankbuckley ?

**Comment by dylankbuckley** [comment]
<img width="635" alt="screen shot 2016-09-15 at 15 40 36" src="https://cloud.githubusercontent.com/assets/8408005/18554042/d3ad3a90-7b5a-11e6-8dcf-385dea0133a8.png">

**Comment by dylankbuckley** [comment]
<img width="635" alt="screen shot 2016-09-15 at 15 40 46" src="https://cloud.githubusercontent.com/assets/8408005/18554050/dd36881e-7b5a-11e6-94fd-721549340d20.png">

**Comment by dylankbuckley** [comment]
Thanks @Kireyin - What do you mean by "Delete the Date comparison operator?" What do I replace it with?

**Comment by Kireyin** [comment]
You don't replace them with anything, those operators are part of Swift 3

**Comment by Kireyin** [comment]
For the "init" issue, not sure I've located the code correctly but
   ```
 func dateByAddingDays(_ days : Int ) -> Date {
      let calendar = Calendar.current
      var dateComponent = DateComponents()
      dateComponent.day = days
      (dateComponent as NSDateComponents).timeZone = TimeZone(secondsFromGMT: 0)
      return calendar.date(byAdding: dateComponent, to: self)!
   }
```
Should work

**Comment by Kireyin** [comment]
For the second issue (second code screened) I just did
`arrSelectedDates.append(cell.currentDate)`

**Comment by Kireyin** [comment]
I can't locate the last code screen
`self.init(timeInterval:0, since:calendar.date(from: dateComponent)!)` should work
The "NSDate" stuff is the issue I would guess

Sorry I can only hint, my locale copy is now too different from the original (and very specific to my use) to b merged here :/

**Comment by dylankbuckley** [comment]
Amazing @Kireyin - So just to confirm, for the operators I got rid of the following:

```
/*
func ==(lhs: Date, rhs: Date) -> Bool {
    return lhs.compare(rhs) == ComparisonResult.orderedSame
}

func <(lhs: Date, rhs: Date) -> Bool {
    return lhs.compare(rhs) == ComparisonResult.orderedAscending
}

func >(lhs: Date, rhs: Date) -> Bool {
    return rhs.compare(lhs) == ComparisonResult.orderedAscending
}
*/
```

**Comment by Kireyin** [comment]
Yes that's it for the operator

I've update my previous comment with what may be a solution

**Comment by dylankbuckley** [comment]
Thanks @Kireyin - Amazing Help!

**Comment by Kireyin** [comment]
My pleasure
Don't hesitate to submit a pull request if everything is working well ;)

**Comment by MobileMon** [comment]
@dylankbuckley please submit a pull request for this

**Comment by dylankbuckley** [comment]
Thinking we should have a Swift3 branch, as these changes will break earlier versions will they not?

**Comment by Kireyin** [comment]
They do if you're not developing with Swift 3
But not developing with Swift 3 is a bad idea so it should be merged in master anyway

@dylankbuckley your PR only includes part of the fixes we made here - please submit another one including all the fixes

**Comment by dylankbuckley** [comment]
@Kireyin have submitted another one which is Swift 3 ready.
