### ISSUE TITLE
Open Calendar in Container View ?

### ISSUE THREAD

**Issue by moheny** [ipraba/EPCalendarPicker#3]
First of all, let me start by saying, this is by far the best comfortable calendar i've touched :+1: .
i'm trying to load the calendar inside a view, or a container view since i want it to fill my empty screen (I do not want a button to load the calendar), is it possible ?

**Comment by ipraba** [comment]
I have released component as a picker controller. Just try adding the viewcontrollers view property to add as subview in another container.

**Comment by moheny** [comment]
Yup I've did what your offer and it's work !
I've did find some bug tho' , let's say the today date is 13-1-16. so the 13 obviously will be in different color. the problem is that 13-2, 13-3 etc... are in the same color of 13-1. 
did you notice it ?

**Comment by ipraba** [comment]
@moheny : Glad it worked for you. 
Regarding the bug. Will check it out and will update it soon. Anyway thanks a lot of notifying the bug.

**Comment by ipraba** [comment]
@moheny I have fixed this bug here https://github.com/ipraba/EPCalendarPicker/commit/e510d0995cc5a9adfad248d5d4d1fd92fd7d1726

**Comment by moheny** [comment]
Thank you so much. Appreciated .

**Comment by lifehappensoutdoors** [comment]
Hello @ipraba, thank you for this useful and well done library. I know that this topic is closed however i was wondering if you elaborate furthermore on how this could be achieved maybe a code segment or some more explanation would be highly appreciated.
