### ISSUE TITLE
Swift 3 update?

### ISSUE THREAD

**Issue by yarodevuci** [ipraba/EPCalendarPicker#33]
are you planning to update pod so it can support Swift 3 syntax?

**Comment by karnett** [comment]
Dev never accepted other pull requests for Swift 3, since my app broke with the iOS 10 update, I had to port it for Swift 3.0...
You're welcome to use it until this project is updated.
pod 'EPCalendarPicker', :git => 'https://github.com/karnett/CalendarPicker.git'

**Comment by yarodevuci** [comment]
Hi. Thanks for the recommendation 
I fixed all the errors myself as well. But will keep in kind your page.

**Comment by keegho** [comment]
Hello karnett i added the Swift 3.0 version but i have several erros. Any solutions?
![screen shot 2016-10-16 at 9 23 09 pm](https://cloud.githubusercontent.com/assets/16656424/19420221/01a6267e-93e7-11e6-84c1-6f1f6b067880.png)

**Comment by yarodevuci** [comment]
Delete those methods

**Comment by jacobokoenig** [comment]
Thanks for that!

**Comment by ipraba** [comment]
Already updated to swift3.0
