### ISSUE TITLE
Crash with swift 3.0

### ISSUE THREAD

**Issue by deepakarora-ios** [ipraba/EPCalendarPicker#39]
app crash on numberOfItemsInSection method of EPCalendarPicker class in swift 3.0.
crash logs  reason: 'the collection view's data source did not return a valid cell from -collectionView:cellForItemAtIndexPath: for index path <NSIndexPath: 0xc000000000000016> {length = 2, path = 0 - 0}'

**Comment by ipraba** [comment]
Already fixed with the new release https://github.com/ipraba/EPCalendarPicker/releases/tag/1.0.9
