### ISSUE TITLE
Incorrect day in month header

### ISSUE THREAD

**Issue by bre7** [ipraba/EPCalendarPicker#4]
Great component ;) I just wanted to report a bug related to day names when weeks start on Monday instead of Sunday.
Even if the labels are updated manually inside the header (EPCalendarHeaderView), `updateWeekendLabelColor` will still color the first and last instead of the last two.

There are several ways to fix this:
- Create a new EPCalendarHeaderView (too much work imo...Unless you reuse the nib)
- Change `updateWeekendLabelColor` and `updateWeekdaysLabelColor` to take `NSCalendar.currentCalendar().firstWeekday` into account. And also change the label values.

Eg:

<p align="center">
<img height="250" alt="screen shot 2016-02-08 at 20 45 35" src="https://cloud.githubusercontent.com/assets/3183848/12903253/1df8564c-cea5-11e5-9d73-85a6dc8d29ab.png"> <img height="250" alt="screen shot 2016-02-08 at 20 46 11" src="https://cloud.githubusercontent.com/assets/3183848/12903254/214e51ac-cea5-11e5-9c16-d8a2216b7399.png">
</p>

**<p align="center">
Feb 1st was Monday
</p>**

**Comment by Urkman** [comment]
I made a pull request for that...

**Comment by ipraba** [comment]
Merged the pull request here https://github.com/ipraba/EPCalendarPicker/commit/cfddf4eef298f50fd7caee820dda44e9a70d8967

**Comment by bre7** [comment]
Ty
