### ISSUE TITLE
Still facing the issue of the repeating current day...

### ISSUE THREAD

**Issue by moheny** [ipraba/EPCalendarPicker#6]
I had it in my last version, but now when updated it to the latest version (1.0.5) i'm still facing the same issue. the current day 15-2 is repeating in all the months (15-3,15-4...) any solution would be appreciated.

**Comment by ipraba** [comment]
Extremely sorry 😔. My bad, forgot to update the podspec. Now updated to 1.0.6, Kindly update your pods 👍
